Implement SequencedDeadLetterQueue for Mongo
AxonFramework/extension-mongo pull request #277
Opened 2022-10-06 12:50 UTC by gklijs

Fixes https://github.com/AxonFramework/extension-mongo/issues/270

A lot was copied from the JPA implementation, with the entries and query code changed to fit Mongo.
This doesn't include transactions, they might be added later by having the `NoTransactionManager` as default.

2022-10-18 13:12 UTC, smcvb requested changes
Great addition so far, @gklijs! Very confident a lot of users will be extremely happy with this. However, I have (as expected) quite some pointers to cover. Not that many conceptual pointers, though.

2022-10-18 13:21 UTC, gklijs commented on .github/workflows/main.yml
> +          ./mvnw -B -U -Dstyle.color=always -Possrh,coverage clean verify
Yes, it used both, otherwise, the coverage report is missing. It does give a warning when there is no ossrh profile, but that's fine.

2022-10-18 13:31 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +     * Returns the index if present on the document, returns {@code null} when not present or document is null
I think this was mainly to move the null check here for the document. I could put the responsibility for the null check to the caller and make this `NotNull`. Still, as there is no schema, there could be something without `id` in there, through indeed, that would be strange.

2022-10-18 13:34 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/MongoSequencedDeadLetterQueue.java
> +        sequenceIdentifierIterator(mongoTemplate.deadLetterCollection(), processingGroup)
https://github.com/AxonFramework/extension-mongo/blob/61d927208528753d5fad156008cd1a54a17c688a/mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java#L469

2022-10-19 12:34 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/MongoSequencedDeadLetterQueue.java
> +            logger.info("Evicting MongoDeadLetter with processing group {} sequence {} and index {}",
Added logging based on the result and changed the message to try instead.

2022-10-19 13:05 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +    private static final String INDEX_KEY = "index";
indeed, as long as we don't use `_id`, it should all be fine.

2022-10-19 13:07 UTC, Morlack commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +    public static Bson uniqueFilter(
I think the name `uniqueFilter` is misnamed. I would prefer the term `findOneFilter` or `singleDlqItemFilter`.
The word unique immediately triggers database unique constraints in my head, which is not what this does

2022-10-19 13:09 UTC, Morlack commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +    public static Bson indexGreaterThanFilter(
Similarly, I think this can be named better. `nextItemInSequenceFilter`, for example

2022-10-19 13:17 UTC, Morlack commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +    public static Bson indexGreaterThanFilter(
In addition, what's the reason for these query specifiers to be in this class? I would expect them in the `DLQ` implementation

2022-10-19 13:19 UTC, Morlack commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/MongoSequencedDeadLetterQueue.java
> +        Document message = entry.asDocument(configuration);
```suggestion
        Document message = entry.asDocument(eventConfiguration);
```
You are not using the instance variable, but always the default. Any customization is lost. 
Remove the line above and change the variable passed into this method

2022-10-19 13:24 UTC, Morlack commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEntry.java
> +    public static Bson uniqueFilter(
Ah, reviewing further, I would suggest these name changes:

`uniqueFilter` -> `bySpecificDeadLetter`
`uniqueNotLockedFilter` -> `bySpecificUnclaimedDeadLetter`
`indexGreaterThanFilter` -> `byProcessingGroupAndIdentifierWithHigherIndex`

It reads pretty nicely:

```
UpdateResult result = mongoTemplate.deadLetterCollection().updateOne(
                bySpecificUnclaimedDeadLetter(
                        processingGroup,
                        deadLetter.sequenceIdentifier(),
                        deadLetter.index(),
                        processingStartedLimit),
                updateProcessingStarted(GenericDeadLetter.clock.instant())
        );
```

2022-10-19 13:29 UTC, Morlack requested changes
I found one small issue and have some suggestions regarding the naming of queries. Other than that, great work!

2022-10-19 14:18 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/InstantEntry.java
> +    public InstantEntry(@Nonnull Document dbInstantEntry) {
Indeed, handling it more neatly now.

2022-10-20 07:37 UTC, gklijs commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/DeadLetterEventEntry.java
> +                .append(TOKEN_TYPE_KEY, tokenType)
yes, but it stores them as null, so only adding them when not null keeps things tidy. So changed it.

2022-10-20 07:51 UTC, gklijs commented on mongo/src/test/java/org/axonframework/extensions/mongo/eventhandling/deadletter/MongoSequencedDeadLetterQueueTest.java
> +
done, green at first attempt 👍

2022-10-21 06:26 UTC, abuijze approved these changes

2022-10-21 08:05 UTC, merged

2022-10-26 12:30 UTC, smcvb commented on mongo/src/main/java/org/axonframework/extensions/mongo/eventhandling/deadletter/MongoSequencedDeadLetterQueue.java
> +            logger.info("Evicting MongoDeadLetter with processing group {} sequence {} and index {}",
Fair choice if you ask me. Thanks for that :+1: